<?php
namespace PhpDevil\framework\modules\migration;
use PhpDevil\framework\base\Module;

/**
 * Class MigrationModule
 * Управление миграциями проекта
 * @package PhpDevil\framework\modules\migration
 */
class MigrationModule extends Module
{
    public function execute($commandName, $params = [])
    {
        parent::execute($commandName, $params); // TODO: Change the autogenerated stub
    }
}